### ISSUE TITLE
dbt 'info' command

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt#3209]
We've been discussing the ability to provide certain information from the rpc server about the current project. Since the rpc server runs on dbt commands, it would need a command line command to provide this information.

An 'info' command could provide lists of macro names, lists of test names, and information about files in the project. Performance would probably not be acceptable until after the partial parsing improvement work is finished, but implementation would not need to wait until then.

It could set the 'partial parse' flag by default, but then we'd probably need a '--no-partial-parse' flag, so it might not be worth the confusion.

Initially at least the information could only be provided from a successful parsing run, so if the dbt user is in the middle of development some things might be outdated.

**Comment by jtcohen6** [comment]
We're thinking about this as a set of RPC-specific methods that return a subset of the information available from the in-memory manifest. In particular, external tools could leverage dbt's internal know-how of file <> node relationships and node selection syntax, rather than having to reimplement those things themselves.

As a goal of our ongoing work around performance and partial parsing, after every hangup (file save), the RPC server should have an up-to-date manifest in memory within 5 seconds. We'll also need to think about:
- What to do if the RPC server gets into a bad state (e.g. parsing error)
- Information available from dbt's "language" (classes, YAML structure, etc) that is not specific to individual projects or represented within the manifest

More to come here!

**Comment by jtcohen6** [comment]
We're definitely going to accomplish this by other means. Tthe next-gen dbt Server will have to have flexible entrypoints into manifest information (project context) and core classes/objects ("language" context)
