### ISSUE TITLE
Using custom schema config results in errors for EU datasets

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [dbt-labs/dbt#3283]
### Describe the bug
We have recently incorporated custom schemas into our dbt packages and have received feedback from customers with EU datasets using BigQuery that their runs fail and they need to override the `+schema` models config in order for their runs to succeed.

### Steps To Reproduce
A customer with an EU dataset runs models successfully. Then the customer adds a `+schema` models config and receives an error that the dataset was not found in the US (due to their datasets being located in the EU).

### Expected behavior
A customer using with an EU dataset without a `+schema` models config has a succesful run, then adds a `+schema` config and is able to successfully run their models with the new custom schema.

### Screenshots and log output
Customer with EU dataset running our Microsoft Ads package receives the below error when using the version of our package with `+schema` config. The solution was to override the models config in their `dbt_project.yml` check [here](https://getdbt.slack.com/archives/C01D1R2JLLA/p1617698421108000) for more details.

```
404 Not found: Dataset XXX:fivetran_microsoft_ads was not found in location US
```

Customer running our Mixpanel package successfully for months upgrades to our version with `+schema` config and receives the following error. The solution was to override the models config in their `dbt_project.yml` check [here](https://github.com/fivetran/dbt_mixpanel/issues/13) for more details.

```
Completed with 1 error and 0 warnings:

Runtime Error in model stg_mixpanel__event_tmp (models/staging/tmp/stg_mixpanel__event_tmp.sql)
  404 GET https://bigquery.googleapis.com/bigquery/v2/projects/backend-producti-b8633498/queries/d53025ae-64dc-4846-802b-2080411adce6?maxResults=0&location=EU&prettyPrint=false: Not found: Job backend-producti-b8633498:EU.d53025ae-64dc-4846-802b-2080411adce6
  
  (job ID: d53025ae-64dc-4846-802b-2080411adce6)

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
Below was compiled from customers using our packages with the dbt version range.
```
[">=0.18.0", "<0.20.0"] 
```

**The operating system you're using:**
Unsure what the customers are using, but will ask.

**The output of `python --version`:**
Unsure what the customers are using, but will ask.

### Additional context
I have noticed the error messages seem to differ from BigQuery, however it does seem the `+schema` models config is the root of the dbt run being confused between US and EU datasets. The above two were the only records I was able to obtain from recent customers, but I have seen this error pop up more frequently. 

It is great that there is a solution to just override the custom schema config, but was wondering if there is an additional config option that could be added to detail the region? I believe this would be covered within the `profiles.yml` but it seemed from the one customer that even with their `profiles.yml` configured properly to EU they still received a similar error.

I apologize in advance if there is a simple workaround for this. I spent some time going through the docs and slack channel, but was not able to find anything.

**Comment by jtcohen6** [comment]
@fivetran-joemarkiewicz Thanks for the detailed report! I'm not quite sure what's going on here, but you've definitely provided a couple interesting leads. There's a lot of confounding variables to this one, but it doesn't _sound_ like an error that necessarily occurs because of the combination of dbt package + custom schema + EU BigQuery.

This isn't the first time we've seen the "dataset not found" error, and there's a solid answer over in https://github.com/fishtown-analytics/dbt/issues/2315:

> This is likely to happen when a dataset is not configured to be multi-region (ie. EU/US) but rather on a single region, like `europe-west2`. Furthermore, BigQuery data located in the EU multi-region is not stored in the `europe-west2` (London) or `europe-west6` (Zürich) data centers.

> My fix for this has been to change the `profiles.yml` file `location` attribute to point at my BQ dataset location, in my case `europe-west2`

I wonder if that could be a piece of what's going on here? From reading through the `dbt-bigquery` plugin code, the `location` parameter in the profile is used when initially instantiating the BigQuery client:

https://github.com/fishtown-analytics/dbt/blob/33dc970859f5535610b2335f8cad5369095a686c/plugins/bigquery/dbt/adapters/bigquery/connections.py#L240-L256

That client parameter has implications, of course, for the region where dbt expects to be querying, creating datasets, creating tables, etc. I'm hopeful that this issue is caused because:
1. The relevant datasets (e.g. `XXX:fivetran_microsoft_ads`) already existed prior to the user running dbt
2. There's a mismatch between that dataset's configured location, and the `location` attribute in the user's `profiles.yml`

In particular, it's possible that a _different_ dbt user created the schema, with a different location specified in `profiles.yml`. Then, a user running later, with a different profile `location`, might see this error.

In any case, I think the best way to debug this is for the users to check the datasets, see if they already exist, and if the data location matches what's specified in their profile. If that doesn't get us anywhere, I'll need to spin up an EU BigQuery account and start reproducing :)

**Comment by fivetran-joemarkiewicz** [comment]
Hi @jtcohen6 thanks so much for digging into this and helping find some possible solutions to the issue these customers are encountering.

I have a suspicion that your proposed solutions will be the fix for the errors I shared. I will loop back up with these customers and do some more digging with the solutions you provided to hopefully confirm these are the reasons for the error messages.

Thanks again!!

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as @jtcohen6 proposed solutions resolved the issue. Thanks again so much! 💯
