### ISSUE TITLE
Load data using dbt seed from .tpl file present in repository

### ISSUE THREAD

**Issue by JyotiSingh7** [dbt-labs/dbt#3519]
### Describe the bug
I have different types of files in my repo - `.csv` and `.tpl` and I want to run `dbt seed` command to load the data in snowflake.
When I run the command, it applies all the `.csv` files and ignores `.tpl` files.
How can I use `dbt seed` for other format data files?

### Steps To Reproduce
In data folder, add few files with `.csv` format and some for `.tpl`
Run `dbt seed` command, it will apply csv files and igonors the tpl files

### Expected behavior
I am looking to load data from different types of files instead of just from `.csv`

### System information
**Which database are you using dbt with?**
- [ ] snowflake

**The output of `dbt --version`:**
```
dbt=0.20.0-b1
```

**Comment by jtcohen6** [comment]
@JyotiSingh7 Thanks for opening, you're in good company (https://github.com/dbt-labs/dbt/issues/2365).

I'm not familiar with `.tpl`-formatted data. (From [what I see online](https://stackoverflow.com/questions/1808294/what-are-tpl-files-php-web-design), it's a way of storing template information, for web development?) Could you provide an example, or a little more by way of the specific use case you're after?

**Comment by JyotiSingh7** [comment]
Hi @jtcohen6 
Thanks for your response. 
To give more context, I have a data folder which contains `.csv` & `.tpl` files. Eg:
- File1.csv
- File2.csv
- File3.csv.tpl

File3.csv.tpl file looks like this:
```
CONFIG_KEY,CONFIG_VALUE,STATUS,DESCRIPTION
HostIP,{{ HOST_NAME }},Y,This is the APP VM Host Name/IP address.
SSHKeyFilePath,{{ SSH_KEY_PATH }},Y,This is the path on APP VM to the SSH key file for Login User
```
I want to replace the variables in my files during runtime and then seed all these files into my snowflake database. What is the best way to handle this use-case?

**Comment by jtcohen6** [comment]
@JyotiSingh7 Got it! Seeds are intended for static data only; they can't take advantage of Jinja templating, as other dbt resources can.

I'd recommend you change `File3.csv.tpl` to be a model instead, and accomplish the runtime templating via dbt-Jinja functions [`var`](https://docs.getdbt.com/reference/dbt-jinja-functions/var) or [`env_var`](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var):
```sql
-- models/File3.sql

select
    'HostIP' as CONFIG_KEY,
    '{{ env_var('HOST_NAME') }}' as CONFIG_VALUE,
    'Y' as STATUS,
    'This is the APP VM Host Name/IP address' as DESCRIPTION

union all

select
    'SSHKeyFilePath' as CONFIG_KEY,
    '{{ env_var('SSH_KEY_PATH') }}' as CONFIG_VALUE,
    'Y' as STATUS,
    'This is the path on APP VM to the SSH key file for Login User' as DESCRIPTION
```

You could get fancier by including the static data in a seed, the dynamic inputs in a model, and joining on a common key.

In the meantime, I'm going to close this issue, since we don't plan to make seed files dynamic.
