### ISSUE TITLE
Change the default dbt packages installation directory to `dbt_packages` from `dbt_modules`

### ISSUE THREAD

**Issue by randypitcherii** [dbt-labs/dbt#3523]
### Describe the feature
Change the default dbt packages installation directory to `dbt_packages` from `dbt_modules`

### Describe alternatives you've considered
Not doing this and living with it.

### Additional context
Just want to have consistent naming, but it's not a huge deal.

### Who will this benefit?
Everyone that uses packages!

### Are you interested in contributing this feature?
_very_ : )

**Comment by jtcohen6** [comment]
Thanks @randypitcherii! I agree that this is the right move. We always call these things "dbt packages," so it's confusing that they're called "dbt modules" the moment they're installed. Plus, the word `modules` has another meaning in dbt—it refers to python modules that are available in the Jinja context ([docs](https://docs.getdbt.com/reference/dbt-jinja-functions/modules)).

Thanks also for contributing some code :) There are a few complications we'll want to proactively address, in addition to the basic change tackled in #3524.

The starter project (created by `dbt init`) doesn't specify `modules-path` in `dbt_project.yml` (everyone uses the default), but it does explicitly specify `'dbt_modules'` in the `clean-targets` and in `.gitignore`. Those are both really important spots we'll need users to make changes:
- In `clean-targets`, so that `dbt clean` + RPC `deps` method appropriately remove those files
- In `.gitignore`, so that installed packages aren't checked into git (this was dropped in the starter project move, I'm adding it back in #3536)

To that end, I think we ought to:
- Rename the project property from `modules-path` to `deps-path` or `packages-install-path`, with backwards compatibility for those currently setting `modules-path`. (I'm leaning toward the latter option, since it's more explicit.)
- Raise a deprecation warning if the user has included `dbt_modules` in their `clean-targets` and has _not_ set `packages-install-path`. That warning should say something like:
```
The default package install path has changed from `dbt_modules` to `dbt_packages`. Please update `clean-targets` in `dbt_project.yml` and `.gitignore`, or set `packages-install-path: dbt_modules` if you'd like to keep the current value.
```

Finally, there are a few docs pages we'll want to update for `next`:
- https://docs.getdbt.com/reference/project-configs/modules-path
- https://docs.getdbt.com/docs/building-a-dbt-project/package-management
