### ISSUE TITLE
Have a variant of dbt --version for packages to help identify outdated packages

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt#3560]
### Describe the feature
`dbt --version` notifies you when there's an updated version of dbt available to you. I'd love if there was an equivalent for packages (`dbt --version packages`?) which listed out each package (similar to #1236) but also checked the hub for updated versions. 

```
Up to date:
  - fishtown-analytics/audit_helper 
      installed version: 0.3.0

  - fivetran/fivetran_log
      installed version: 0.3.1

Updates available:
  - fishtown-analytics/dbt_utils: 
      installed version: 0.6.6 
      latest version:    0.7.0

Update your versions in packages.yml, then run dbt deps
```

### Additional context
- Not sure if/how this would work for packages loaded via git directly
- Not sure what should happen for packages installed via dependencies. E.g. 
    - Should having `calogica/dbt_expectations` mean that `calogica/dbt_date` is shown? My guess: maybe
    - Should it show there's an update available for `dbt_date` if it's only installed via dependency? My guess: probably not - that's for the dependency-creating package owner to deal with, and it's probably not helpful to make people wonder how to update something they can't control.

### Who will this benefit?
People who would like the latest and greatest from their packages, but don't want to manually go through the hub for their half-dozen different packages

### Are you interested in contributing this feature?
Sure, given ample pointers!

**Comment by jtcohen6** [comment]
@joellabes I like it!

What if this were part of `dbt deps` output? Something like:
```bash
$ dbt deps
Running with dbt=0.19.2
Installing fishtown-analytics/dbt_utils@0.6.6
  Installed from version 0.6.6
  Latest version: 0.7.0
Installing fishtown-analytics/codegen@0.3.1
  Installed from version 0.3.1
  Latest version: 0.4.0
Installing fivetran/fivetran_utils@0.1.1
  Installed from version 0.1.1
  
Updates available for: dbt_utils, codegen
```

A few quick thoughts:
- This could only work for Hub-installed packages. I don't think it could work for git-installed packages. That's ok, it's one of the benefits of using the package registry.
- The input would have to be information from `packages.yml`, rather than the actual installed packages in `dbt_modules`. Packages don't record their version anywhere within their own project code—the version is the git tag in their repo. (I try to keep the `version` in `dbt_project.yml` up to date for Labs-maintained packages, but that's cosmetic only and not enforced.) So this command wouldn't be able to help with keeping `packages.yml` + `dbt_modules` in harmony, only `packages.yml` + the wider world.

If that version sounds reasonable to you, I think this could indeed be a good first issue

**Comment by joellabes** [comment]
Yes I'm OK with all of that! Including it in deps output is much more discoverable.

In your example, is fivetran_utils' latest version not shown because it's up to date, or because 
>Packages don't record their version anywhere within their own project code

makes it unknowable?

**Comment by jtcohen6** [comment]
I was thinking because it's the latest version. Could be:
```
Installing fivetran/fivetran_utils@0.1.1
  Installed from version 0.1.1
  Up to date!
```

Anything installed from git/local wouldn't be knowable.

**Comment by joellabes** [comment]
Sweet! Let's do it

**Comment by sungchun12** [comment]
@joellabes Are you going to own building this feature for `dbt deps`? If not, I'd be happy to tackle this!

**Comment by joellabes** [comment]
@sungchun12 I'm not likely to get to it in the next month or so, so if you want to jump in earlier then go for gold!

**Comment by sungchun12** [comment]
> @sungchun12 I'm not likely to get to it in the next month or so, so if you want to jump in earlier then go for gold!

Thanks a bunch for the baton pass 😄 . I'll officially own this and start this week!

**Comment by sungchun12** [comment]
@joellabes Feel free to take a look at the pull request, and let me know if the terminal output examples solves the issue you're seeing!
