### ISSUE TITLE
Fix flaky tracking integration tests

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt#3561]
Postgres integration test suite 033 matches expected and actual tracking events. However, the experimental parser fires its tracking event non-deterministically. Commits 7a32129, and c43c5fa were supposed to fix this, yet [circleci](https://app.circleci.com/pipelines/github/dbt-labs/dbt/3023/workflows/cee21f06-bbc4-4b47-a12b-339259f430b9/jobs/44132) still sees inconsistent failures. 

This set of tests may not actually be all that useful as is and we may want to rework how we test events going forward anyway.

**Comment by leahwicz** [comment]
If this test is flaky and we don't have an obvious way to fix it, can we comment it out for now just to unblock CI?

**Comment by kwigley** [comment]
We can definitely do that! But, that will only address tests that directly test tracking events. There are still intermittent failures in other tests ([example](https://app.circleci.com/pipelines/github/dbt-labs/dbt/3086/workflows/004c075d-aa64-4799-923d-efd3154db623/jobs/44459)). This is because some tests bootstrap a (sometimes incomplete) project config and this doesn't always initialize the global current user. Since there are tracking events being sent non-deterministically when parsing model files, some tests are hitting this code path that expect an initialized global user! I tried to address this in https://github.com/dbt-labs/dbt/pull/3604

**Comment by leahwicz** [comment]
Thanks @kwigley! Just unblocking ourselves here for now will be super helpful and then we can dive deep on what is actually going on with these tests and make them more stable.
