### ISSUE TITLE
dbt docs generate never results in development

### ISSUE THREAD

**Issue by hazal-sener** [dbt-labs/dbt#3592]
Hi,
### Describe the bug
We are facing an issue regarding to “dbt docs generate” in development environment. It seems that although all the steps passed successfully, document generation never ends running, and it blocks the command so I can’t execute anything else. It remains at Building Catalog and never pass to Catalog written to be ended.

### Steps To Reproduce
Production (scheduled jobs) generates the documentation about 1minute and half in spite of having problems in development. I kindly ask to assist me on the reason why documentation generation never can be completed and always keep running in development while everything is fine in deployment.

### Expected behavior
I would like to have dbt docs generate command works properly in development environment like it does in deployment.

What can be the difference between development and deployment that can cause this?  What has to be checked to get rid of this issue?

### Screenshots and log output
![image](https://user-images.githubusercontent.com/77548765/126151656-2fc0bc86-0afb-45c7-9356-4b5bd9deb6bc.png)

It stucks at Building Catalog
![image](https://user-images.githubusercontent.com/77548765/126154061-2f0ed2cd-bd84-481e-998c-34f33f34e776.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
0.19.1

**The operating system you're using:**

**The output of `python --version`:**
3.7.0
### Additional context
Add any other context about the problem here.

I would appreciate if you can support me on this.
Thanks
Kind Regards,
Hazal Sener

**Comment by jtcohen6** [comment]
@hazal-sener Thanks for opening this issue. It sounds like this is most likely a bug with the dbt Cloud IDE, as opposed to a bug with the RPC server `docs.generate` task—especially since you're using dbt v0.19.1, which could successfully generate docs in the IDE for several months.

Would you mind sending a message into dbt Cloud support? I'm going to close this issue, only because I don't believe the fix will happen in the dbt Core codebase. All the same, feel free to link to this issue for additional context when discussing with support.
