### ISSUE TITLE
Using `error_if` without `warn_if` defaults to `warn_if: "> 0"`

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt#3611]
### Describe the bug
When you use `error_if` without `warn_if`, and the test failure falls below the `error_if` threshold, a warning is raised.

### Steps To Reproduce
- Get a column with `n` failing tests
- Set a `error_if:` to `n + 1`
- Run the test

### Expected behavior
No warning to be raised.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - bigquery: 0.20.0
  - snowflake: 0.20.0
  - redshift: 0.20.0
  - postgres: 0.20.0
```

**The operating system you're using:** Mac

**The output of `python --version`:** 3.8.10

**Comment by jtcohen6** [comment]
@jaypeedevlin Thanks for opening! This one is interesting.

The current behavior treats test severity as a gradient: `ERROR > WARN > PASS`. By default (`severity: error`), dbt checks the `error_if` condition first, then the `warn_if` condition second, and finally passes if neither is met. (If `severity: warn`, dbt skips over the `error_if` check entirely.)

The appeal of this approach is that users can set and check multiple thresholds for the same test, e.g. error if more than 100 failures, warn if more than 10, otherwise pass.

In the current setup, both `error_if` and `warn_if` conditions are set to `!= 0` by default. If you only set `error_if`, the `warn_if` config will still be `!= 0`. So in order to error with >= 5 records, _and pass otherwise_, you need to be set both configs:
```yml
tests:
  - not_null:
      error_if: ">= 5"
      warn_if:  ">= 5"  # will only warn if severity=warn
    # warn_if: "is not null and false" # never warn
```

My underlying view here is that, if a test returns rows / a nonzero `fail_calc`, it has failures. That's true even if that test has an `error_if` condition set, and the condition is unmet—it still has failures, and it should raise a warning, unless there's a specified and unmet `warn_if` config to indicate otherwise.

In order to change this behavior, I think we'd need to set `warn_if: None` by default, and check whether the user has set it before making a comparison. That would enable us to pass over warning and jump straight to pass, in the case where the user hasn't set `warn_if` and `severity: error`. I'm not sure what we'd want to do in the case where `severity: warn` and `warn_if` is unset, though.

Here's a rough diagram I was using to map this out:

![Screen Shot 2021-07-27 at 11 44 09 PM](https://user-images.githubusercontent.com/13897643/127260224-3fd6f946-bffd-4d65-9bea-48a0826a9f8a.png)

Personally, I find the current behavior to be the right mix of powerful and intuitive, so I'm leaning toward `wontfix`. That said, if you have other ideas, I'm always open to hearing them!

**Comment by jaypeedevlin** [comment]
Since opening this I discussed it with the team internally, and it turns out there was a mix of expectations on how this should behave — some had the expectation I had, and others expected it the way it is.

I'm happy for this to be a wontfix and just chalk it up to me having wonky expectations of how this would behave!
