### ISSUE TITLE
dbt 0.20.0 - BigQuery massive increase in test costs

### ISSUE THREAD

**Issue by StijnZanders** [dbt-labs/dbt#3633]
### Describe the bug
After the recent change in dbt 0.20.0 where tests return erroneous rows instead of the number of erroneous rows (`COUNT(*)`) our test costs have increased 5 fold. This is because for example a `not_null` test returns all columns instead of just the number of incorrect rows. Thus it requires much more data to test.

### Steps To Reproduce
For example the difference in a `not_null` test between 0.19.2 and 0.20.0

### Expected behavior
Only the data that is needed to test is queried

### Screenshots and log output
Not null test in dbt 0.20.0:
```
select *
from `project_id`.`dataset_id`.`table_id`
where column is null
```

Not null test in dbt 0.19.2
```
select count(*) as validation_errors
from `project_id`.`dataset_id`.`table_id`
where column is null
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

### Additional context
I get that this is a feature of dbt 0.20.0, but it's quite a big increase in costs for us. Having a feature flag to just return the `COUNT(*)` would be great. We'll be reverting to dbt 0.19.2 for now.

**Comment by jtcohen6** [comment]
@StijnZanders Thanks for opening the issue! I'm sensitive to any negative consequences from the changes to tests in v0.20, so I want to be sure I'm understanding you right.

While the compiled `not_null` test query is now `select *` instead of `select count(*)`, the _test materialization_ still wraps that query in `select count(*)`:

https://github.com/dbt-labs/dbt/blob/9c58f3465bf9907a2b62942de548f80650cd6288/core/dbt/include/global_project/macros/materializations/test.sql#L6-L15

So for a built-in `not_null` test, dbt is actually running this query:

```sql
select
    count(*) as failures,
    count(*) != 0 as should_warn,
    count(*) != 0 as should_error
from (
    select *
    from `project_id`.`dataset_id`.`table_id`
    where event_id is null
) dbt_internal_test
```

When I check the following queries in the BigQuery console for cost estimates, testing 100 MB table, I see:
1. Compiled test SQL, 0.19.2 (`select count(*)`): 3.7 MB
2. Compiled test SQL, 0.20.0 (`select *`): 100 MB
3. Actual `dbt test`, 0.19.2 (same as compiled): 3.7 MB
3. Actual `dbt test`, 0.20.0 (wrapped in materialization): 3.7 MB
4. `dbt test --store-failures`, 0.20.0: 100 MB

There is an additional cost for `--store-failures`, since this feature does want to select and store all columns for easier dev-time debugging. That can a worthwhile trade-off, since dev time is expensive!

There's one additional test feature in v0.20.0 that we introduced, particularly with a mind for cost savings on BigQuery: [the `where` config](https://docs.getdbt.com/reference/resource-configs/where). If you have a large partitioned table—especially a table that requires a partition filter—it's much easier now to filter on that table accordingly.

```yml
models:
  - name: my_big_partitioned_table
    description: "Incremental model, rebuilt for the past 3 days"
    columns:
      - name: my_column
        tests:
          - not_null:
              where: "date_partition_column > date_add(current_date, interval -3 day)"
```

If any of the premises I've shared above is incorrect, I definitely want to know. Are you seeing an increase in your BigQuery billing simply from running `dbt test`, after upgrading from 0.19.2 to 0.20.0?

**Comment by StijnZanders** [comment]
@jtcohen6 thanks for the elaborate background info!

I see, the compiled tests changed but what's eventually run with `dbt test` doesn't as it's wrapped.
This impacted us as we run the compiled tests in Airflow and not `dbt test` via the CLI.

For now I'll have to mimic the wrapping in our "`dbt_test_operator`", eventually we'd want to move to run `dbt test` itself through the k8s operator, but that's a bit too much work for now.

So this only impacts custom implementations of running dbt tests as those queries have changed. But I recognize that that's needed for storing test failures.

Feel free to close the issue

**Comment by jtcohen6** [comment]
@StijnZanders Ah, thanks for the context on how you're deploying tests today. In a future version of dbt, I'd love to offer a "full materialization SQL" for each node, in addition to just `compiled_sql`, since there are important steps that happen in the materialization wrapping layer. That's always been true for models and snapshots, now for tests too.
