### ISSUE TITLE
new config - sources: required_explicit: true

### ISSUE THREAD

**Issue by dbrtly** [dbt-labs/dbt#3697]
### Describe the feature

Sometimes projects compile but won't run because they refer to a relation that doesn't exist. Often they are a typo.
Request a new config boolean toggle under sources for 'required)_explicit'.
When on all references to database relations that don't use ref() or source() are flagged as compilation errors.

### Describe alternatives you've considered

```
dbt init new_proj
cd new_proj
{
        echo 'sources:'
        echo '  require_explicit: true'
} >> dbt_project.yml
{
    echo '-- Use the `ref` function to select from other models'
    echo ''
    echo 'select *'
    echo 'from  my_first_dbt_model'
    echo 'where id = 1'
    echo ''
} > models/example/my_second_dbt_model.sql
dbt compile
```
should throw error something like:

```
Have you forgotten to import a source? Your project is configured to require explicit sources but a relation contains an implicit source.
error: implicit source
    models/example/my_second_dbt_model.sql
    no source has been defined for 'my_first_dbt_model'.
```

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

No.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

It's a method to encourage good code hygiene. 
Explicit is better than implicit. Shift left on capturing bugs.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

Absolutely. I'll need a little help but if you point me to the files and we can chat about it. I'd love to.

**Comment by jtcohen6** [comment]
@dbrtly Neat idea! I totally get the desire to enforce DAG relationships between sources and models. I don't necessarily agree with making this a `sources` config; I also think there's a way to accomplish what you're after with existing constructs and a little bit of custom/plugin code.

When dbt runs, it parses your project into an internal representation, which we call a manifest or `graph`. That manifest is available at execution time, including in the Jinja context. You can write a macro like:
```sql
{% macro check_all_models_have_parents() %}

  {% if execute %}
    {% for node in graph.nodes.values() %}
      {# does this model have at least one ref() call or source() call? #}
      {% if node.resource_type == 'model' and not node.refs and not node.sources %}
        {% do exceptions.raise_compiler_error(node.name ~ " has no ref() or source() calls") %}
      {% endif %}
    {% endfor %}
  {% endif %}

{% endmacro %}
```

Then include that macro as an `on-run-start` project hook:
```yml
# dbt_project.yml

on-run-start:
  - "{{ check_all_models_have_parents() }}"
```

If you have any models missing a `ref` or `source` call, you'll quickly find out:
```
-- models/model_a.sql
select *
from my_first_dbt_model
where id = 1
```
```sql
$ dbt run
Running with dbt=0.20.1
Found 3 models, 5 tests, 0 snapshots, 1 analysis, 148 macros, 1 operation, 1 seed file, 2 sources, 1 exposure

14:07:48 |
14:07:48 | Running 1 on-run-start hook
Database error while running on-run-start
Encountered an error:
Compilation Error in operation testy-on-run-start-0 (./dbt_project.yml)
  model_a has no ref() or source() calls

  > in macro check_all_models_have_parents (macros/check.sql)
  > called by operation testy-on-run-start-0 (./dbt_project.yml)
  > called by operation testy-on-run-start-0 (./dbt_project.yml)
  ```

This approach is similar to the one taken by the [`dbt_meta_testing` package](https://hub.getdbt.com/tnightengale/dbt_meta_testing/latest/), which allows users to set expectations around tests and descriptions. The macros in that package parse `graph.nodes.values()`, and raise an error if the expectations aren't met.

There's a similar approach in the same vein: leverage dbt metadata in tooling _outside_ of dbt. The most useful information from the internal manifest is written out to [an artifact `manifest.json`](https://docs.getdbt.com/reference/artifacts/manifest-json) at the end of project parsing. Yo
You can inspect `manifest.json` and raise an error if it doesn't conform to expectations; perhaps as a CI check or before committing code. That's just what the `pre-commit-dbt` package exists to do, and it looks like there's a check for 
[model parents and children](https://github.com/offbi/pre-commit-dbt/blob/main/HOOKS.md#check-model-parents-and-childs):
```yml
hooks:
  # every model must have at least one parent
  - id: check-model-parents-and-childs
    args: ["--min-parent-cnt", "1", "--"]
```

I'm going to close this issue for the time being, since I believe existing dbt constructs can get you the thing you're after. That said, I wouldn't be surprised if we revisit this topic, and add native support for quality checking / enforcement in the future, such as with a model config such as `require_parents`.
