### ISSUE TITLE
UNION ALL issue when running snapshots with invalidate_hard_deletes=True

### ISSUE THREAD

**Issue by inkeysolutions** [dbt-labs/dbt#3710]
### Describe the bug
When enabling invalidate_hard_deletes, the initial snapshot works but subsequent attempts fail with error:
`Column 5 in UNION ALL has incompatible types: DATETIME, DATETIME, TIMESTAMP at [119:5]`.
Other considerations:
- the snapshot works fine when `invalidate_hard_deletes` is omitted and run multiple times
- selecting fields individually (as opposed to a `select *`) does not make a difference
- the snapshot table was dropped and recreated between attempts of switching `invalidate_hard_deletes` on and off
- I can reproduce this issue on any table

### Steps To Reproduce
snapshot config:
```
{% snapshot snap_company %}

{{
    config(
        target_schema=generate_schema_name('edw_ods', model),
        unique_key='id',
        strategy='timestamp',
        updated_at='updatedAt',
        invalidate_hard_deletes=True,
    )
}}

select
    *
from {{ ref('company') }}

{% endsnapshot %}
```
run `dbt snapshot -s snapshots/snap_company.sql` twice

### Expected behavior
The snapshot should work identically on the initial and subsequent runs

### Screenshots and log output
n/a

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - snowflake: 0.20.0
  - postgres: 0.20.0
  - redshift: 0.20.0
  - bigquery: 0.20.0
```

**The operating system you're using:**
Debian
**The output of `python --version`:**
Python 3.8.2

**Comment by jtcohen6** [comment]
@inkeysolutions Thanks for opening!

The issue here is that your `updatedAt` column is of type `datetime`, whereas `dbt-bigquery` uses [`snapshot_get_time`](https://github.com/dbt-labs/dbt/blob/1a984601ee964fff59e338805ab49a1e8489e342/core/dbt/include/global_project/macros/materializations/snapshot/snapshot.sql#L120) &rarr; [`current_timestamp`](https://github.com/dbt-labs/dbt/blob/1a984601ee964fff59e338805ab49a1e8489e342/core/dbt/include/global_project/macros/materializations/snapshot/strategies.sql#L59) &rarr; [`CURRENT_TIMESTAMP()`](https://github.com/dbt-labs/dbt/blob/1a984601ee964fff59e338805ab49a1e8489e342/plugins/bigquery/dbt/include/bigquery/macros/adapters.sql#L97) as the input to `dbt_valid_to` when capturing hard deletes.

If you cast your column to `timestamp` first, this should succeed:
```sql
{% snapshot snap_company %}

{{
    config(
        target_schema=generate_schema_name('edw_ods', model),
        unique_key='id',
        strategy='timestamp',
        updated_at='updated_at_ts',
        invalidate_hard_deletes=True,
    )
}}

select
    *, timestamp(updatedAt) as updated_at_ts
from {{ ref('company') }}

{% endsnapshot %}
```
Then it should work just fine!

In the best-case scenario, dbt should dynamically determine whether to use `current_timestamp` or `current_datetime`, based on the data type of the column you've set as `updated_at`. That might be doable, but it's going to be tricky to implement. We do something clever to get a `null` value of the correct type, and thereby secure the union:

https://github.com/dbt-labs/dbt/blob/1a984601ee964fff59e338805ab49a1e8489e342/core/dbt/include/global_project/macros/materializations/snapshot/snapshot.sql#L51

I'm not sure if/how to repeat the magic trick for a not-null value, picking between `current_timestamp`, `current_date`, or `current_datetime`.

So, if I had to pick one, I think `timestamp` is the way to go. I don't see a reason to ever prefer a `datetime` column (no timezone information) to a `timestamp` column (includes timezone info) when it comes to crucial metadata columns in a snapshot; it's also easy enough to turn a `date` into `timestamp`, though not the other way around. I'm thinking that the right next step here is to [document](https://docs.getdbt.com/docs/building-a-dbt-project/snapshots#timestamp-strategy-recommended) that, at least on BigQuery, snapshots' `updated_at` really must be of type `timestamp`, when using the `timestamp` strategy.

If you feel strongly about using `datetime` across the board, you could reimplement the `snapshot_get_time` macro in your own project, and have it return a datetime instead:
```
{% macro snapshot_get_time() %}
    {{ return('CURRENT_DATETIME') }}
{% endmacro %}
```

I'm going to close this issue for now, but if you have another idea, or think I missed something above, we can re-open!
