### ISSUE TITLE
Support a --greedy flag that turns on all indirect selection. Otherwise, log nodes that weren't selected indirectly

### ISSUE THREAD

**Issue by EPNickBosma** [dbt-labs/dbt#3723]
### Describe the feature
When I use `dbt test --models some_model` or `dbt test --models +exposure:some_exposure_name` it would be nice if tests like `relationships:` that refer to other models were explicitly skipped, rather than just silently refusing to go.

### Describe alternatives you've considered
I now know that in the case of specific models I can just use graph operators to make sure all of the tests do run, so instead of the above I would use `dbt test --models some_model+1`.  Interestingly, however, I have not been able to make this work with exposures in the same way. (I think this is because exposures are already to the right of the DAG, so the + behaves differently or is simply redundant in that case.) 

### Additional context
The danger here is simply in not knowing. It's fine if certain tests don't run for certain reasons. It's less fine that there's zero warning when it happens. To my mind this would be a great implementation of the `Skipped` statistic when testing.

I was caught unaware by the behavior shift in 0.20.0, so I didn't know that my core assumption around testing, namely: _"When I test a model, all tests that I've put against that model will be run"_, no longer held true. I now understand how and (broadly) why the behavior shifted, but I still think there's a valid point to be made here. 

I thought my tests were all passing, because none were failing and none were being skipped. All I saw was green, so I was pressing on with the project. Once I figured out what was happening and ran all of the tests, I found out the data I had been working with was flawed in ways I thought I was actively protecting against. 

### Who will this benefit?
Going forward, it will be beneficial for myself and others to be told that certain tests are being skipped when testing specific models without graph operators, or testing through exposures.

An analyst or engineer who sees that 100% of the tests they're running against a model are passing might think that is brilliant news; everything works. They might later (hopefully not too much later) discover that yes 100% of the running tests passed, but some that were not being run at all would have failed spectacularly.

An analyst or engineer who sees that 100% of the tests they're running against a model are either passing or being skipped will immediately look into why the tests are being skipped, and will not face the same kind of danger.

### Are you interested in contributing this feature?
I don't think I'm the best person to write code around this, but I am happy to discuss it further if there would be value in that.

**Comment by jtcohen6** [comment]
@EPNickBosma Thank you for the thoughtful write-up! You make a really compelling point. This is something I've been thinking about, especially after hearing confusion from a few folks relating to the change in v0.20. I still stand by that change, and the rationale underpinning it, but we could have done better to communicate "this test used to run here, now it no longer does."

I think there are two options here, of quite different complexities:
- (Easy) Log a message at the start of `dbt test` listing tests that were candidates for indirect selection, but ultimately not selected because they have a parent missing
- (Hard) Selecting those tests to run, and having them explicitly `SKIP` when their name comes up

That difference is aesthetic and functional. Tests included in the selection criteria, and then skipped during the course of the invocation, would be included in `run_results.json` with the status `SKIP`. Today, skipped results only appear in that artifact if one of their parents _fails_ while running.

For reasons of difficulty and consistency, I'm leaning toward the info logging. What do you think?

**Comment by joellabes** [comment]
@jtcohen6 I can make a separate issue for this, but how interested would you be in something like a `--greedy` flag? I've had a few stabs at it now (including with Nick yesterday), and haven't worked out how to write a selector that would consistently give the same behaviour as the old way. (If there is a way, feel free to share!)

I think the new behaviour is great for CI etc, but "run _every_ test in the tests block for this model" is a pretty reasonable and common use case.

**Comment by jtcohen6** [comment]
@joellabes I'm so open to that. Let's do it.

I feel strongly that the new, less-greedy behavior is the right one to have by default. At the same time, I'm in no way opposed to the old behavior, and acknowledge it's highly desirable in some cases.

That could be a separate issue, or it could be neatly rolled into this one: Support a `--greedy` flag. Log an info message when tests haven't been greedily selected (default behavior), and include in that message a helpful hint that users can re-run with the `--greedy` flag to include those tests.

Even for that more-complex implementation, I think we could neatly fit that logic into the methods I linked above.

**Comment by joellabes** [comment]
>or it could be neatly rolled into this one

Yes, it feels like this is now a "add a `--greedy` flag" ticket, which has the cherry on top of "make the flag discoverable via a log message". If you point me in the right direction, I can have a crack at some point!

**Comment by jtcohen6** [comment]
Right on! I just attempted a retitle of this issue accordingly, let me know if I'm wide of the mark :)

This code can get tricky. The methods I linked above are fair entry points, and we could probably wire it up using just those. There's also some cool stuff we could do leveraging the new-since-0.20 [`greedy`](https://github.com/dbt-labs/dbt/blob/454168204c90464de1753ced824f5e3417e6203a/core/dbt/graph/selector_spec.py#L69) boolean property of `SelectionCriteria`, which changes the behavior of [how unions and set differences are calculated](https://github.com/dbt-labs/dbt/blob/454168204c90464de1753ced824f5e3417e6203a/core/dbt/graph/cli.py#L28-L71). It likely requires a bit of both.
