### ISSUE TITLE
Build Open API spec for future dbt-core work.

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt#3730]
Pursuant to creating a thin client + server model for `dbt-core`, we'll need to generate an Open API spec to define the necessary interface between client(s) and server(s).  This ticket is to do that work.

Repo to use: https://github.com/dbt-labs/dbt-core-spec
Starting point:  At a bare minimum we can start with a spec for our existing RPC server and then build from there.

**Comment by owlas** [comment]
Hey @iknox-fa - tried to access the link but I think it's private!

**Comment by jtcohen6** [comment]
Hey @owlas! We're iterating on this pretty rapidly, and a _lot_ has changed since Ian posted this issue six weeks ago. As soon as we have information we can share publicly—about a new dbt Server, and a thinner CLI client to work with it—we'll be discussing it in this repo (and likely some others as well).

I appreciate that we're in a bit of a limbo period. It's no secret that the existing `dbt rpc` server is not long for this world; at the same time, the dbt Server 2.0 is very much still in the lab.

In the meantime, I'm going to close this issue. More to come :)

**Comment by owlas** [comment]
Exciting thanks!
