### ISSUE TITLE
Support permanent tables as a part of table materialization

### ISSUE THREAD

**Issue by utkamishra** [dbt-labs/dbt#3753]
Describe the feature
Please allow us to insert data by creating a permanent table in the config. Right now if we use table materialization with select statements within it, it creates transient table by default whereas I want it to create permanent table somehow.

https://github.com/dbt-labs/dbt/blob/dev/marian-anderson/plugins/snowflake/dbt/include/snowflake/macros/materializations/table.sql

Describe alternatives you've considered
Put a transient flag in table materialization which can be set to 'True', 'False' as per need. Setting to 'True' shall create a transient table while 'False' can create a permanent table.
I could create a custom materialization that does what is described, but the change seems sufficiently small and useful to go in DBT's materialization.

Additional context
Snowflake offers two alternatives to permanent tables- temporary tables and transient tables. Temp tables are dropped at the end of the session while transient tables must be explicitly dropped, otherwise they incur charges. DBT's table materialization currently forces users to use transient tables, and this should be opt-out.

Who will this benefit?
Users that need permanent tables for their projects. Projects that have less frequent logic changes to their intermediate transforms, as well as large datasets, fit this description.

Are you interested in contributing this feature?
I would be willing to make this change

**Comment by jtcohen6** [comment]
@utkamishra Thanks for opening! dbt-snowflake does support a `transient` config that lets you turn table transience on or off. I'll share a few brief comments below; check out the docs for a full explanation: https://docs.getdbt.com/reference/resource-configs/snowflake-configs#transient-tables

By default, dbt creates transient tables because:
- dbt _can_ drop and recreate each table from scratch, so long as your modeling logic is idempotent (it should be!)
- dbt _expects_ to drop and recreate each `table`-materialized model from scratch, each time it runs
- It costs storage to keep around all those extra backups

You can easily switch this off any place you set resource configs:
```yml
# dbt_project.yml
models:
  transient: false
```
```sql
-- models/my_specific_model.sql
{{ config(transient = false) }}
select 1 as id
```
