### ISSUE TITLE
Include database and schema fields into the list task json output

### ISSUE THREAD

**Issue by juma-adoreme** [dbt-labs/dbt#3778]
### Imporevement description
Update List Task JSON output (`dbt ls --output json`) to include `database` and `schema` fields. In the current released version (0.20.1),  both fields are available under the `config` field, but the `schema` disregards custom generated schema names (using macros), and the `database` field is always null.

After the update JSON output will look like below (irrelevant fields removed):
```
{
  "unique_id": "model.my_project.my_table",
  "name": "my_table",
  "database": "my_database",
  "schema": "stg-my_schema",  
  "alias": "my_table",
  "original_file_path": "models/my_table.sql",
  "config": {
    "alias": null,
    "schema": "my_schema",
    "database": null
  }
}
```

### Use case example 
This is useful for the promotion of objects from one environment to another. For example, my data pipelines look like this: 
1. Run DBT DAG with staging profile. The naming macro creates objects with some prefix 
2. Run tests on the stage data objects, if everything is good:
3. Promote objects to production. 
So, I need to know which objects were in the DAG, their names in the database, and how they should be named in the target environment. (`dbt ls --output json -t stg and `dbt ls --output json -t prd`)

### Implementation
I'm happy to contribute to the implementation of this improvement. I have implemented this locally, ran integration tests, and willing to create a pull request.

**Comment by jtcohen6** [comment]
@juma-adoreme Thanks for opening the issue, and for the PR! I'm not opposed to this change; I'm _really_ interested in implementing the more general-purpose solution proposed in (#3395).

What do you think about taking this one step further, by parametrizing the set of `ALLOWED_KEYS` in the `list` task, and making it possible (as a user) to pass your own custom `--output-keys`? That way, rather than needing to open a PR here next time you want some additional fields, you could simply:
```
dbt ls --output json --output-keys unique_id name database schema alias original_file_path config
```

I think that would be fairly simple to implement:
- Add a new flag/argument to the `list` subparser [here](https://github.com/dbt-labs/dbt/blob/9e796671dd55d4781284d36c035d1db19641cd80/core/dbt/main.py#L822-L829)
- Update [`generate_json`](https://github.com/dbt-labs/dbt/blob/9e796671dd55d4781284d36c035d1db19641cd80/core/dbt/task/list.py#L111-L117) to check first for `self.args.output_keys`, otherwise use the default `ALLOWED_KEYS` (similar to the logic for [`resource_types`](https://github.com/dbt-labs/dbt/blob/9e796671dd55d4781284d36c035d1db19641cd80/core/dbt/task/list.py#L147-L162))

**Comment by juma-adoreme** [comment]
@jtcohen6, thank you! This makes perfect sense. Just to confirm, we will not have a list of available choices for the --output-keys argument, am I right? Otherwise, we return to the problem of the editing `ALLOWED_KEYS` if some new key will appear. 
And if the user passes some inexistent keys, the ls task will return an empty dictionary `{}`

**Comment by jtcohen6** [comment]
@juma-adoreme That sounds right to me. This is a "more advanced" feature, and it feels reasonable to tell folks that they have to know which keys they want (the key names are all the same as they are in `manifest.json`, so that helps).

So too, if they pass an invalid key, dbt should return an empty result, or (probably better) an error saying as much. It will be important to test that for keys that are defined on some resource types and not others.
