### ISSUE TITLE
Tests are not working with ClickHouse

### ISSUE THREAD

**Issue by artamoshin** [dbt-labs/dbt#3872]
### Describe the bug
Any dbt generic test (not_null, unique...) are not work with ClickHouse database.  
Command `dbt test` raises error `0.0 is not of type 'boolean'` due to TestRunner.execute_test expect that test_result_dct must be (int, bool, bool), but ClickHouse [doesn't support boolean type](https://clickhouse.tech/docs/en/sql-reference/data-types/boolean/).

### Steps To Reproduce
Just create a simplest model and schema:
**model.sql**
```sql
SELECT 100 AS column
```
**schema.yml**
```yaml
version: 2

models:
  - name: model
    columns:
      - name: column
        tests:
          - not_null
```

### Expected behavior
The test should be passed.

### Screenshots and log output
```
$ dbt test
Running with dbt=0.20.1
Found 1 model, 1 test, 0 snapshots, 0 analyses, 156 macros, 0 operations, 0 seed files, 0 sources, 0 exposures

06:09:43 | Concurrency: 1 threads (target='dev')
06:09:43 |
06:09:43 | 1 of 1 START test not_null_model_column.............................. [RUN]
Unhandled error while executing test.clickhouse_test.not_null_model_column.035b1e767a
0.0 is not of type 'boolean'

Failed validating 'type' in schema['properties']['should_warn']:
    {'type': 'boolean'}

On instance['should_warn']:
    0.0
06:09:43 | 1 of 1 ERROR not_null_model_column................................... [ERROR in 0.09s]
06:09:43 |
06:09:43 | Finished running 1 test in 0.21s.

Completed with 1 error and 0 warnings:

0.0 is not of type 'boolean'

Failed validating 'type' in schema['properties']['should_warn']:
    {'type': 'boolean'}

On instance['should_warn']:
    0.0

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: ClickHouse)

**The output of `dbt --version`:**
```
installed version: 0.20.1
   latest version: 0.20.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.20.1
  - redshift: 0.20.1
  - bigquery: 0.20.1
  - snowflake: 0.20.1
  - clickhouse: 0.20.1
```

**The operating system you're using:**
Ubuntu 20.04.2 LTS on Windows 10 WSL

**The output of `python --version`:**
Python 3.8.10

### Additional context
ClickHouse version is 21.8.5.7.
Latest version of dbt is 0.20.2, but there are no same version of ClickHouse adapter.

**Comment by jtcohen6** [comment]
@artamoshin Thanks for the issue! The fix for this should actually come in the `dbt-clickhouse` adapter, so I'd encourage you to reopen the issue over there: https://github.com/silentsokolov/dbt-clickhouse

We offer support for different syntax support on different data warehouse adapters by means of [dispatched macros](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch). The maintainers of `dbt-sqlserver` raised a very similar issue (https://github.com/dbt-labs/dbt/issues/3465, https://github.com/dbt-labs/dbt/pull/3461), because SQLServer also does not support boolean types (!). To support this pattern, the global dbt `'test'` materialization calls a dispatched macro, named `get_test_sql`. It also defines the default version (`default__get_test_sql`), which expects to work on many (but not all) dbt warehouses.

The solution here for ClickHouse should look much the same as the solution for SQLServer. The adapter simply needs to reimplement the `get_test_sql` macro, [like so](https://github.com/dbt-msft/dbt-sqlserver/blob/4091a07a5bdb7b5bac521fc72d8da52fabcd6c16/dbt/include/sqlserver/macros/materializations/test.sql#L1-L12):

```sql
{% macro clickhouse__get_test_sql(main_sql, fail_calc, warn_if, error_if, limit) -%}
    select
      {{ fail_calc }} as failures,
      case when {{ fail_calc }} {{ warn_if }}
        then 'true' else 'false' end as should_warn,
      case when {{ fail_calc }} {{ error_if }}
        then 'true' else 'false' end as should_error
    from (
      {{ main_sql }}
      {{ "limit " ~ limit if limit != none }}
    ) dbt_internal_test
{%- endmacro %}
```

(Why `'true'` and `'false'` as strings? dbt expects these values to be boolean, so it will use python type coercion to see if they can be. That doesn't work for `0.0`, though, hence the error you're seeing. See: https://github.com/dbt-msft/dbt-sqlserver/pull/141#discussion_r657394468)

I'm going to close this issue, as I believe the resolution for it should come in the form of adding a `clickhouse__get_test_sql` macro to the `dbt-clickhouse` adapter plugin.
