### ISSUE TITLE
Enable deprecation: dispatch-packages

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt#3895]
### dispatch-packages

Introduced in: v0.19.2
In the last week, raised by: 276 projects (~9% of eligible projects)

Instead of raising a deprecation warning when the user has defined the `packages` arg, or has passed a list instead of a string, we should instead raise a clear error. That error message should point to the same documentation that the [deprecation warning message](https://github.com/dbt-labs/dbt/blob/9d7a6556efb9bdbbfedf24b6f01ded90595a572d/core/dbt/deprecations.py#L46-L57) currently does 

https://github.com/dbt-labs/dbt/blob/96083dcaf51ab7725f1b554891581e1522e32d7d/core/dbt/context/providers.py#L137-L140

Then, we can:
- Remove `DispatchPackagesDeprecation` from the list of active deprecations
- Significantly simplify the logic (removing jank backwards compatibility) from [`jinja_static.py`](https://github.com/dbt-labs/dbt/blob/develop/core/dbt/clients/jinja_static.py) — to discuss with @gshank 

_Originally posted by @jtcohen6 in https://github.com/dbt-labs/dbt/issues/2798#issuecomment-919998174_

**Comment by emmyoop** [comment]
https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch will also need an update.

**Comment by emmyoop** [comment]
@jtcohen6 Should I rip out the `packages` arg all together or leave it in for now and just raise an exception when it's used?

**Comment by jtcohen6** [comment]
@emmyoop I think I prefer leaving it in and raising an explicit exception when it's used explicitly. That feels like the same approach as raising an explicit exception when a list is passed to the second positional argument.

At the same time, we should feel _very_ comfortable removing all the code from [`jinja_static.py`](https://github.com/dbt-labs/dbt/blob/3789acc5a7b3f71b4e333ac6e235c62ee0c957f5/core/dbt/clients/jinja_static.py#L87) that exists to handle values being passed to `packages`. This was all for backwards compatibility, since we had to rework `dispatch` in a patch release (v0.19.2) to fix some regressions from v0.19.1.
