### ISSUE TITLE
SQL Alchemy and Killing Pandas

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [dbt-labs/dbt#3921]
### Describe the features

Support using SQL Alchemy to create SQL for models as a strategy to combat Pandas scripts.

### Describe alternatives you've considered

Building a Pandas mock API that calls SQL Alchemy to build equivalent SQL queries so I can drop a Pandas script into a SQL pipeline work minimal problems.

### Additional context

I hate translating Pandas to SQL, and Pandas scales terribly. Unfortunately, it's defacto for many data science uses because it's honestly a great tool for that use case.

SQL Alchemy is one step closer to SQL for data science uses. If I could translate Pandas to SQL Alchemy via Monkey patching, then SQL comes free.

### Who will this benefit?

Data scientists and those translating their work could use the same tools.

### Are you interested in contributing this feature?

Yes

**Comment by jtcohen6** [comment]
@aidan-plenert-macdonald Broadly, I share your sentiment that data preparation pipelines, written as pandas transformations, will scale much more successfully as dbt models. What you're proposing is a bit out of left field, relative to the functionality of dbt-core today. One of the principal expectations of dbt models is that they're written as SQL—or, at least, that they _compile_ to SQL. Therein lies the possibility, I suppose.

What exactly are you imagining here? Would a dbt model contain code like:
```python
-- models/my_model.py
OtherModel = ref('my_other_model')

my_new_model = session
    .query(OtherModel)
    .filter(OtherModel)
    .column_name == 'value')
    .all()
```
Instead of:
```sql
-- models/my_model.sql

select * from {{ ref('my_other_model') }}
where column_name = 'value' 
```
And then it would be on dbt-core (or a dbt-sqlalchemy plugin) to compile that into raw SQL, and execute it against the database?

Personally, I find the latter expression much more readable than the former! I get that's the thrust of your issue—I'm me, and many folks with data science backgrounds prefer to read & write the former.

My instinct here is to say that this should instead be tooling that exists outside of dbt-core, which can translate from SQL Alchemy into dbt-SQL, allowing data scientists to write the first and then contribute/deploy their code as the second.

**Comment by aidan-plenert-macdonald** [comment]
Yeah. That was my proposal. An outside adapter is fine. Thanks!
