### ISSUE TITLE
dbt Tasks got randomly killed (sigterm) in Cloud Composer 

### ISSUE THREAD

**Issue by stevenzhang-support** [dbt-labs/dbt#3960]
### Describe the bug
The issue is tasks in Cloud Composer got randomly killed (sigterm).
Logging query to show the errors:
resource.type="cloud_composer_environment" resource.labels.location="<location>" resource.labels.environment_name="<environment name>" timestamp>="2021-09-25T19:00:45.396Z" severity>=ERROR " **Received SIGTERM. Terminating subprocesses**."

### Steps To Reproduce
1. Create a  Cloud Composer environment
2. install https://pypi.org/project/dbt/ and run dtbt task

### Expected behavior
No error like "ERROR - Received SIGTERM. Terminating subprocesses." received

### Screenshots and log output
NA

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
``` ==0.20.1
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by jtcohen6** [comment]
@stevenzhang-support It looks like that error and the associated log message are coming from Cloud Composer, not from dbt Core. Is that right?

Given that, I'm not sure how I can help here. It looks like this error message could be the result of insufficient memory, or of subprocesses being cleaned up too quickly (especially if they're long-running):
- https://groups.google.com/g/cloud-composer-discuss/c/nhMC0AhqugA?pli=1
- https://stackoverflow.com/questions/54313601/airflow-signals-sigterm-to-subprocesses-unexpectedly

I'm going to close this issue, since I don't believe the resolution for this bug will come in the form of a code change to `dbt-core`. I'd be happy to reopen if you're able to identify a particular behavior of dbt-core that's not working as it should, or not working the way you expect, thereby making it difficult to deploy via Cloud Composer.

**Comment by stevenzhang-support** [comment]
thanks
