### ISSUE TITLE
Provide warning in case of wrong key in config

### ISSUE THREAD

**Issue by franciscofonseca0** [dbt-labs/dbt#3976]
### Describe the feature
When a wrong key is used in the `config` of a model, i.e, _incremental_stegy_ instead of _incremental_strategy_, 

```
{{
  config(
    materialized = 'incremental',
    incremental_stegy = 'insert_overwrite',
    partition_by = {'field': 'order_date', 'data_type': 'date'},
    partitions = partitions_to_replace
  )
}}
```
no warning or error is raised as the `macro` responsible for retrieving this information is using `config.get('...')` and attributing a default value, in this case `merge`.

### Describe alternatives you've considered
There really isn't an alternative, it would just be nice to have a warning or an error for these cases

### Additional context
I have only tried in `bigquery` but i believe this error is agnostic to the database

### Who will this benefit?
Everyone who needs to do a little big of weird debugging in `dbt` from time to time :)

### Are you interested in contributing this feature?
For sure

**Comment by jtcohen6** [comment]
@franciscofonseca0 I totally agree. I think this will be tricky to implement, given the ability of users to pass any configs they'd like into `config()`, and to define custom macros and materializations that make use of those user-defined configs.

There's an open issue for the same feature request over in https://github.com/dbt-labs/dbt/issues/2606. I just left a comment there with some updated thinking. In the meantime, I'm going to close this issue as a duplicate, so that we can keep the conversation in one place.
