### ISSUE TITLE
DBT without addons

### ISSUE THREAD

**Issue by pixie79** [dbt-labs/dbt#3980]
Hi,

I have been trying to install DBT 0.20.2 on the AWS Managed Apache Airflow instances via their requirements.txt.
(It used python3.7)

This appears to have issues due to conflicting modules and gets stuck in a loop. Mostly this appears to be related to the snowflake-connector-python requiring pyarrow<3.1.0,>=3.0.0 which it would appear in not available.

If there a way to not include the additional connectors and only ones which people specify via the requirements.txt (being the only method on managed instances to control what gets installed).

There also seems to be a hard requirement on GIT which I am not sure is needed, but again this breaks the install.

May be there is the option of a DBT minimal package instead?

Thanks

Mark

**Comment by jtcohen6** [comment]
@pixie79 Which database are you using with dbt? I highly recommend that you install the specific adapter you need:
```
pip install dbt-<adapter>
# e.g. pip install dbt-redshift
```
This will install just `dbt-core` and the dependencies of your specific adapter. (In fact, the `dbt-postgres` adapter is a dependency of `dbt-redshift`, so that will be installed too.)

So long as you're not using Snowflake, you won't need to install `dbt-snowflake` or any of its unique dependencies.

In fact, we're moving all dbt installation in this direction, so as to avoid exactly the problem you've identified. I'm going to close this issue, since we're taking such steps as we speak.
