### ISSUE TITLE
Custom `bigquery__create_table_as` macro no longer overrides built-in macro in version 0.21.0

### ISSUE THREAD

**Issue by bthomee** [dbt-labs/dbt#4029]
### Describe the bug
One of my macros overrides the built-in [`bigquery__create_table_as`](https://docs.getdbt.com/docs/contributing/building-a-new-adapter#adapter-dispatch) macro, however it no longer gets called in 0.21.0 whereas it did get called in 0.20.2 and before.

### Steps To Reproduce
Add a macro like:

```
{% macro bigquery__create_table_as(temporary, relation, sql) -%}
  {{ log('override bigquery__create_table_as') }}
  ... 
{%- endmacro %}
```

When you run dbt 0.20.2 you will see the log statement in dbt.log, whereas in dbt 0.21.0 it is missing.

### Expected behavior
The overridden macro should be called in 0.21.0.

### Screenshots and log output
N/A

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 0.21.0

Up to date!

Plugins:
  - redshift: 0.21.0
  - bigquery: 0.21.0
  - postgres: 0.21.0
  - snowflake: 0.21.0
```

**The operating system you're using:**
```
# uname -r
5.10.47-linuxkit
```

FWIW I run dbt within a custom-built Docker image:
```
FROM gcr.io/google.com/cloudsdktool/cloud-sdk:slim
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache-dir dbt==0.21.0 && \
    apt-get install gettext-base
```

**The output of `python --version`:**
```
# python --version
bash: python: command not found
# python3 --version
Python 3.7.3
```

### Additional context
N/A

**Comment by jtcohen6** [comment]
@bthomee This did change in v0.21, as a trade-off to unlock other capabilities (https://github.com/dbt-labs/dbt/pull/3851). Global macros now specify the `dbt` namespace when searching for dispatch candidates.

You have two options to get this working again, both quite straightforward:

- Name your local version as `create_table_as`, instead of `bigquery__create_table_as`. This overrides the _entire_ `create_table_as` macro. It's only possible to do this for macros defined in your root project.
- Add a `dispatch` config to your `dbt_project.yml`, telling dbt to prefer your candidate (adapter-prefixed) macros over the built-in ones when dispatching the `dbt` namespace:
```yml
# dbt_project.yml
dispatch:
  - macro_namespace: dbt
    search_order: ['<name_of_your_root_project>', 'dbt']
```

There are [docs](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch#overriding-global-macros) for this, added when we released v0.21. At the same time, I think a clearer outline of how macro override works is totally warranted, including the differences between macros in the root project / packages / internal (adapter) packages. That feeling is prompted by this issue, and a few slack threads [here](https://getdbt.slack.com/archives/C37J8BQEL/p1633508980310600?thread_ts=1633377998.228400&cid=C37J8BQEL) and [here](https://getdbt.slack.com/archives/C50NEBJGG/p1633633247051000).

In the meantime, I'm going to close this issue, since the equivalent functionality is possible through other means.
