### ISSUE TITLE
DBT models saving in default schema instead of custom schema.

### ISSUE THREAD

**Issue by pratikcgd** [dbt-labs/dbt#4044]
### Describe the bug
I tried to save models on custom schemas specifying it in dbt_project.yml file but the generated models are saving in default schema. 
PS- The same code was working previously. It works after closing the VS code and starting it again.

### Steps To Reproduce
![image](https://user-images.githubusercontent.com/86762371/136889981-b2c12a68-41ea-4689-af8d-8935d77092d5.png)

### Expected behavior
The files in /models/folder should save in custom schema.

### System information
**Which database are you using dbt with?**
- bigquery

**The output of `dbt --version`:**
version --- 0.20.1

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
3.9.6

**Comment by jtcohen6** [comment]
@pratikcgd Thanks for opening!

> It works after closing the VS code and starting it again.

This feels like a crucial detail. Is there any chance of a delay between when you edit the file in VS Code, and when VS Code update the version of the local file actually saved on disk? `dbt run` will use the version saved on disk, rather than the text being visually displayed to you in your text editor.

Alternatively, I can ask the obligatory question for debugging custom schemas: do you have a macro named `generate_schema_name` saved in your project's `macros/` directory?

**Comment by jtcohen6** [comment]
To be clear, I'm _pretty_ sure this has nothing to do with dbt, but rather an idiosyncrasy of your local file system / text editor. I'm going to close for the time being, but I'm happy to reopen if you have new details to share.
